language: node_js

node_js:
  - 12

cache:
  directories:
    - node_modules
env:
  - CI=true
script:
  - npm run build:storybook

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: storybook-static
  on:
    branch: master

notifications:
  email:
    recipients:
      - 1170212530@qq.com
    on_success: never
    on_failure: always
